(lang dune 3.15)

(name confluence_site_converter)
(version 8902cf3-dirty)

(generate_opam_files true)

(source
 (github haruki-sugarsun/confluenece_site_converter))

(authors "Haruki Sato")

(maintainers "Haruki Sato")

(license LICENSE)

(homepage "https://github.com/haruki-sugarsun/confluenece_site_converter")
(documentation "https://github.com/haruki-sugarsun/confluenece_site_converter")

 (package
 (name confluence_site_converter)
 (synopsis "A short synopsis")
 (description "A longer description")
 (depends (ocaml (>= 5.1)) (dune (>= 3.15)) core core_unix ppx_jane lwt)
 (tags
  (topics "to describe" your project)))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/dune-files.html#dune-project
