# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # SETUP
      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          # Version of the OCaml compiler to initialise
          ocaml-compiler:  4.14.1
      - run: opam install --yes ocamlfind core.v0.14.1 cohttp-lwt-unix cohttp-async lambdasoup yojson lwt_ssl

      # BUILD
      - name: build
        run: |
          eval $(opam env)
          make

      # Upload the last artifact.
      - uses: actions/upload-artifact@v3
        with:
          name: latest-executable
          path: |
            confluence_site_converter
